github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
tasks: 
  - init: echo "source /workspace/vedenemo/.aliases" >> ~/.bashrc && cd vedenemo.core && mvn install -DskipTests && cd ../vedenemo.cli && mvn install  -DskipTests && java -cp /workspace/vedenemo/vedenemo.cli/target/vedenemo.cli-1.0-SNAPSHOT.jar:/workspace/vedenemo/vedenemo.core/target/vedenemo.core-1.0-SNAPSHOT.jar com.vedenemo.cli.VedenemoCli

vscode:
  extensions:
    - vscjava.vscode-maven@0.21.2:tFEkt2FqLujaNTLU5AmRiQ==
    - vscjava.vscode-java-test@0.24.2:K9XH858+UGOKjfN3qRW15Q==
    - SonarSource.sonarlint-vscode@1.17.0:ykgEHpHsIPlCEJ+/QYVcrw==
    - usernamehw.errorlens@3.1.1:E43ZI7EpaYPnQJQM1+2bZw==